#############################################################################
# Makefile for building: gallery.app/Contents/MacOS/gallery
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  gallery.pro
# Template: app
# Command: /Users/qbanconsulting/Qt5.7.1/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile gallery.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../../5.7/clang_64/lib/QtQuickControls2.framework/Headers -I../../../../5.7/clang_64/lib/QtQuick.framework/Headers -I../../../../5.7/clang_64/lib/QtGui.framework/Headers -I../../../../5.7/clang_64/lib/QtQml.framework/Headers -I../../../../5.7/clang_64/lib/QtNetwork.framework/Headers -I../../../../5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../../5.7/clang_64/mkspecs/macx-clang -F/Users/qbanconsulting/Qt5.7.1/5.7/clang_64/lib
QMAKE         = /Users/qbanconsulting/Qt5.7.1/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = gallery1.0.0
DISTDIR = /Users/qbanconsulting/Qt5.7.1/Examples/Qt-5.7/quickcontrols2/gallery/.tmp/gallery1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/qbanconsulting/Qt5.7.1/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/qbanconsulting/Qt5.7.1/5.7/clang_64/lib -framework QtQuickControls2 -framework QtQuick -framework QtQml -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = gallery.cpp qrc_gallery.cpp
OBJECTS       = gallery.o \
		qrc_gallery.o
DIST          = ../../../../5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../../5.7/clang_64/mkspecs/qdevice.pri \
		../../../../5.7/clang_64/mkspecs/features/device_config.prf \
		../../../../5.7/clang_64/mkspecs/common/unix.conf \
		../../../../5.7/clang_64/mkspecs/common/mac.conf \
		../../../../5.7/clang_64/mkspecs/common/macx.conf \
		../../../../5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../../5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../../5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../5.7/clang_64/mkspecs/common/clang.conf \
		../../../../5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../../5.7/clang_64/mkspecs/qconfig.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../../5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../../5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../5.7/clang_64/mkspecs/features/spec_post.prf \
		../../../../5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../5.7/clang_64/mkspecs/features/toolchain.prf \
		../../../../5.7/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../../5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../../5.7/clang_64/mkspecs/features/default_post.prf \
		../../../../5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../../5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../../5.7/clang_64/mkspecs/features/qt.prf \
		../../../../5.7/clang_64/mkspecs/features/resources.prf \
		../../../../5.7/clang_64/mkspecs/features/moc.prf \
		../../../../5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../../5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../../5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../../5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../../5.7/clang_64/mkspecs/features/yacc.prf \
		../../../../5.7/clang_64/mkspecs/features/lex.prf \
		gallery.pro  gallery.cpp
QMAKE_TARGET  = gallery
DESTDIR       = 
TARGET        = gallery.app/Contents/MacOS/gallery


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d gallery.app/Contents/MacOS/ || mkdir -p gallery.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: gallery.pro ../../../../5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../../../5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../../5.7/clang_64/mkspecs/qdevice.pri \
		../../../../5.7/clang_64/mkspecs/features/device_config.prf \
		../../../../5.7/clang_64/mkspecs/common/unix.conf \
		../../../../5.7/clang_64/mkspecs/common/mac.conf \
		../../../../5.7/clang_64/mkspecs/common/macx.conf \
		../../../../5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../../5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../../5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../5.7/clang_64/mkspecs/common/clang.conf \
		../../../../5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../../5.7/clang_64/mkspecs/qconfig.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../../5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../../5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../5.7/clang_64/mkspecs/features/spec_post.prf \
		../../../../5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../5.7/clang_64/mkspecs/features/toolchain.prf \
		../../../../5.7/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../../5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../../5.7/clang_64/mkspecs/features/default_post.prf \
		../../../../5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../../5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../../5.7/clang_64/mkspecs/features/qt.prf \
		../../../../5.7/clang_64/mkspecs/features/resources.prf \
		../../../../5.7/clang_64/mkspecs/features/moc.prf \
		../../../../5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../../5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../../5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../../5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../../5.7/clang_64/mkspecs/features/yacc.prf \
		../../../../5.7/clang_64/mkspecs/features/lex.prf \
		gallery.pro \
		gallery.qrc \
		../../../../5.7/clang_64/lib/QtQuickControls2.framework/QtQuickControls2.prl \
		../../../../5.7/clang_64/lib/QtQuick.framework/QtQuick.prl \
		../../../../5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../../5.7/clang_64/lib/QtQml.framework/QtQml.prl \
		../../../../5.7/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../../../5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile gallery.pro
../../../../5.7/clang_64/mkspecs/features/spec_pre.prf:
../../../../5.7/clang_64/mkspecs/qdevice.pri:
../../../../5.7/clang_64/mkspecs/features/device_config.prf:
../../../../5.7/clang_64/mkspecs/common/unix.conf:
../../../../5.7/clang_64/mkspecs/common/mac.conf:
../../../../5.7/clang_64/mkspecs/common/macx.conf:
../../../../5.7/clang_64/mkspecs/common/sanitize.conf:
../../../../5.7/clang_64/mkspecs/common/gcc-base.conf:
../../../../5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../5.7/clang_64/mkspecs/common/clang.conf:
../../../../5.7/clang_64/mkspecs/common/clang-mac.conf:
../../../../5.7/clang_64/mkspecs/qconfig.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../5.7/clang_64/mkspecs/features/qt_functions.prf:
../../../../5.7/clang_64/mkspecs/features/qt_config.prf:
../../../../5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../5.7/clang_64/mkspecs/features/spec_post.prf:
../../../../5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../../../5.7/clang_64/mkspecs/features/toolchain.prf:
../../../../5.7/clang_64/mkspecs/features/mac/toolchain.prf:
../../../../5.7/clang_64/mkspecs/features/default_pre.prf:
../../../../5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../5.7/clang_64/mkspecs/features/resolve_config.prf:
../../../../5.7/clang_64/mkspecs/features/default_post.prf:
../../../../5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../../../5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../5.7/clang_64/mkspecs/features/qml_debug.prf:
../../../../5.7/clang_64/mkspecs/features/warn_on.prf:
../../../../5.7/clang_64/mkspecs/features/qt.prf:
../../../../5.7/clang_64/mkspecs/features/resources.prf:
../../../../5.7/clang_64/mkspecs/features/moc.prf:
../../../../5.7/clang_64/mkspecs/features/unix/opengl.prf:
../../../../5.7/clang_64/mkspecs/features/unix/thread.prf:
../../../../5.7/clang_64/mkspecs/features/file_copies.prf:
../../../../5.7/clang_64/mkspecs/features/mac/rez.prf:
../../../../5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../../5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../../../5.7/clang_64/mkspecs/features/exceptions.prf:
../../../../5.7/clang_64/mkspecs/features/yacc.prf:
../../../../5.7/clang_64/mkspecs/features/lex.prf:
gallery.pro:
gallery.qrc:
../../../../5.7/clang_64/lib/QtQuickControls2.framework/QtQuickControls2.prl:
../../../../5.7/clang_64/lib/QtQuick.framework/QtQuick.prl:
../../../../5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../../../../5.7/clang_64/lib/QtQml.framework/QtQml.prl:
../../../../5.7/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../../../5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile gallery.pro

qmake_all: FORCE

gallery.app/Contents/PkgInfo: 
	@test -d gallery.app/Contents || mkdir -p gallery.app/Contents
	@$(DEL_FILE) gallery.app/Contents/PkgInfo
	@echo "APPL????" > gallery.app/Contents/PkgInfo
gallery.app/Contents/Resources/empty.lproj: 
	@test -d gallery.app/Contents/Resources || mkdir -p gallery.app/Contents/Resources
	@touch gallery.app/Contents/Resources/empty.lproj
	
gallery.app/Contents/Info.plist: 
	@test -d gallery.app/Contents || mkdir -p gallery.app/Contents
	@$(DEL_FILE) gallery.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.gallery,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,gallery,g" -e "s,@LIBRARY@,gallery,g" -e "s,@TYPEINFO@,????,g" ../../../../5.7/clang_64/mkspecs/macx-clang/Info.plist.app >gallery.app/Contents/Info.plist

all: Makefile \
		gallery.app/Contents/PkgInfo \
		gallery.app/Contents/Resources/empty.lproj \
		gallery.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents gallery.qrc $(DISTDIR)/
	$(COPY_FILE) --parents gallery.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r gallery.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_gallery.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_gallery.cpp
qrc_gallery.cpp: gallery.qrc \
		../../../../5.7/clang_64/bin/rcc \
		gallery.qml \
		qtquickcontrols2.conf \
		images/arrows@3x.png \
		images/menu@4x.png \
		images/arrow@4x.png \
		images/drawer@4x.png \
		images/arrows@2x.png \
		images/menu@3x.png \
		images/drawer.png \
		images/arrow@3x.png \
		images/back@4x.png \
		images/drawer@3x.png \
		images/menu@2x.png \
		images/arrow@2x.png \
		images/back@3x.png \
		images/drawer@2x.png \
		images/qt-logo@4x.png \
		images/arrows.png \
		images/menu.png \
		images/qt-logo.png \
		images/back@2x.png \
		images/qt-logo@3x.png \
		images/arrow.png \
		images/qt-logo@2x.png \
		images/arrows@4x.png \
		images/back.png \
		images/+material/back@4x.png \
		images/+material/menu@3x.png \
		images/+material/menu.png \
		images/+material/drawer.png \
		images/+material/drawer@4x.png \
		images/+material/back@3x.png \
		images/+material/menu@2x.png \
		images/+material/back.png \
		images/+material/drawer@3x.png \
		images/+material/back@2x.png \
		images/+material/drawer@2x.png \
		images/+material/menu@4x.png \
		pages/GroupBoxPage.qml \
		pages/TextFieldPage.qml \
		pages/ProgressBarPage.qml \
		pages/PopupPage.qml \
		pages/RangeSliderPage.qml \
		pages/SliderPage.qml \
		pages/TabBarPage.qml \
		pages/TumblerPage.qml \
		pages/StackViewPage.qml \
		pages/TextAreaPage.qml \
		pages/ScrollablePage.qml \
		pages/SpinBoxPage.qml \
		pages/ScrollBarPage.qml \
		pages/DelegatePage.qml \
		pages/SwitchPage.qml \
		pages/RadioButtonPage.qml \
		pages/ComboBoxPage.qml \
		pages/ScrollIndicatorPage.qml \
		pages/ToolTipPage.qml \
		pages/DrawerPage.qml \
		pages/CheckBoxPage.qml \
		pages/DialPage.qml \
		pages/BusyIndicatorPage.qml \
		pages/PageIndicatorPage.qml \
		pages/FramePage.qml \
		pages/SwipeViewPage.qml \
		pages/MenuPage.qml \
		pages/ButtonPage.qml
	/Users/qbanconsulting/Qt5.7.1/5.7/clang_64/bin/rcc -name gallery gallery.qrc -o qrc_gallery.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean 

####### Compile

gallery.o: gallery.cpp ../../../../5.7/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../../../5.7/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../../5.7/clang_64/lib/QtQml.framework/Headers/QQmlApplicationEngine \
		../../../../5.7/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../../../../5.7/clang_64/lib/QtQml.framework/Headers/QQmlContext \
		../../../../5.7/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		../../../../5.7/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../../5.7/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		../../../../5.7/clang_64/lib/QtQuickControls2.framework/Headers/QQuickStyle \
		../../../../5.7/clang_64/lib/QtQuickControls2.framework/Headers/qquickstyle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gallery.o gallery.cpp

qrc_gallery.o: qrc_gallery.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_gallery.o qrc_gallery.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/Users/qbanconsulting/Qt5.7.1/Examples/Qt-5.7/quickcontrols2/gallery || mkdir -p $(INSTALL_ROOT)/Users/qbanconsulting/Qt5.7.1/Examples/Qt-5.7/quickcontrols2/gallery
	$(DEL_FILE) -r $(INSTALL_ROOT)/Users/qbanconsulting/Qt5.7.1/Examples/Qt-5.7/quickcontrols2/gallery/gallery.app
	
	-$(INSTALL_DIR) gallery.app $(INSTALL_ROOT)/Users/qbanconsulting/Qt5.7.1/Examples/Qt-5.7/quickcontrols2/gallery/gallery.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/qbanconsulting/Qt5.7.1/Examples/Qt-5.7/quickcontrols2/gallery/gallery.app
	-$(DEL_DIR) $(INSTALL_ROOT)/Users/qbanconsulting/Qt5.7.1/Examples/Qt-5.7/quickcontrols2/gallery/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

